-- CRIANDO BASE DE DADOS

CREATE DATABASE AC2

-- ALTERAR PARA A BASE DE DADOS

USE AC2

-- CRIANDO TABELA

CREATE TABLE TB_CLIENTES
(
	CPF					INT			NOT NULL	,
	NOME				CHAR(20)	NOT NULL	,
	PONTUACAO			INT			NOT NULL	,
	TELEFONE			CHAR(20)	NOT NULL	,
	COD_PROBLEMA		INT			NOT NULL	,
	OBSERVACOES			CHAR(100)	NOT NULL	

	CONSTRAINT PK_CPF	PRIMARY KEY(CPF)
)

CREATE TABLE TB_PROBLEMAS 
(
	COD_PROBLEMA        INT			NOT NULL	,
	DESCRICAO			CHAR(50)	NOT NULL
)	

INSERT INTO TB_PROBLEMAS
(COD_PROBLEMA, DESCRICAO)
VALUES
(123, 'CARRO APRESENTA PROBLEMAS')

SELECT * FROM TB_PROBLEMAS
SELECT * FROM TB_CLIENTES

--DROP TABLE TB_CLIENTES

DROP TABLE TB_CLIENTES





