SELECT TOP (1000) [CPF]
      ,[NOME]
      ,[PONTUACAO]
      ,[TELEFONE]
      ,[COD_PROBLEMA]
      ,[OBSERVACOES]
  FROM [AC2].[dbo].[TB_CLIENTES]

INSERT INTO TB_CLIENTES
(CPF, NOME, PONTUACAO, TELEFONE, COD_PROBLEMA, OBSERVACOES)
VALUES
(111111111, 'ANTONIO', 2, '11 66667777', 123, 'TRANSAÇÃO NEGADA')

-- ACESSAR ARQUIVO POR VISUAL STUDIO CODE