-- ATIVIDADE CONTINUA 01 - BANCO DE DADOS

-- TABELAS DO MENOS IMPORTANTE AO MAIS IMPORTANTE

-- CRIANDO BANCO DE DADOS
CREATE DATABASE CONCESSIONARIA

-- USANDO BANCO DE DADOS
USE CONCESSIONARIA

-- TABELA ANO
CREATE TABLE TB_ANO
(
	ID_ANO		 INT       IDENTITY(1,1), -- CHAVE PRIMÁRIA
	ANO			 INT	      NOT NULL

	CONSTRAINT PK_ID_ANO     PRIMARY KEY(ID_ANO)
)

-- TABELA MES
CREATE TABLE TB_MES
(
	ID_MES		  INT	   IDENTITY(15,3), -- CHAVE PRIMARIA
	MES		      INT	   NOT NULL

	CONSTRAINT PK_ID_MES    PRIMARY KEY(ID_MES)
)

-- TABELA MODELO
CREATE TABLE TB_MODELO
(
	ID_MODELO			   INT			IDENTITY(1,1), -- CHAVE PRIMARIA
	DESCRICAO			   VARCHAR(50)	NOT NULL

	CONSTRAINT PK_ID_MODELO         PRIMARY KEY (ID_MODELO)
)

-- TABELA FABRICANTE
CREATE TABLE TB_FABRICANTE
(
	ID_FABRICANTE      INT                  IDENTITY(1,1), -- CHAVE PRIMARIA
	NOME		       VARCHAR(50)          NOT NULL,
	CIDADE			   VARCHAR(50)          NOT NULL,
	ENDERECO		   VARCHAR(100),
	UF				   CHAR(2), -- VARIÁVEL FIXA	
	TELEFONE		   VARCHAR(20),
	CONTATO			   VARCHAR(50)			 NOT NULL

	CONSTRAINT PK_ID_FABRICANTE  PRIMARY KEY (ID_FABRICANTE)
)

-- TABELA VEICULO
CREATE TABLE TB_VEICULO
(
	ID_VEICULO			INT			    IDENTITY(1,1), -- CHAVE PRIMARIA
	DESCRICAO			VARCHAR(50)	    NOT NULL,
	VALOR				DECIMAL(8,2)	NOT NULL,
	ID_MODELO			INT,
	ID_FABRICANTE		INT,
	ID_ANO_FABRICACAO   INT			    NOT NULL,
	DATA_COMPRA			DATE			NOT NULL

	CONSTRAINT PK_ID_VEICULO            PRIMARY KEY (ID_VEICULO),

	CONSTRAINT FK_ID_MODELO             FOREIGN KEY(ID_MODELO)
	REFERENCES TB_MODELO(ID_MODELO),

	CONSTRAINT FK_ID_FABRICANTE         FOREIGN KEY (ID_FABRICANTE)
	REFERENCES TB_FABRICANTE(ID_FABRICANTE),

	CONSTRAINT FK_ID_ANO_FABRICACAO     FOREIGN KEY(ID_ANO_FABRICACAO)
	REFERENCES TB_ANO(ID_ANO)
)

-- TABELA VENDAS
CREATE TABLE TB_VENDAS
(
	ID_VENDAS				 INT		IDENTITY(1,1), -- CHAVE PRIMARIA
	QTD						 TINYINT    NOT NULL,
	ID_VEICULO				 INT,
	ID_ANO_DA_VENDA			 INT, -- ANO
	ID_MES_DA_VENDA			 INT  -- MES

	CONSTRAINT PK_ID_VENDAS           PRIMARY KEY (ID_VENDAS),

	CONSTRAINT FK_ID_VEICULO          FOREIGN KEY(ID_VEICULO)
	REFERENCES TB_VEICULO(ID_VEICULO),

	CONSTRAINT FK_ID_ANO_DA_VENDA     FOREIGN KEY (ID_ANO_DA_VENDA)
	REFERENCES TB_ANO(ID_ANO),

	CONSTRAINT FK_ID_MES_DA_VENDA     FOREIGN KEY(ID_MES_DA_VENDA)
	REFERENCES TB_MES(ID_MES)
)

SELECT * FROM TB_ANO -- RECUPERANDO AS TABELAS DO BD
SELECT * FROM TB_MES -- RECUPERANDO AS TABELAS DO BD
SELECT * FROM TB_MODELO -- RECUPERANDO AS TABELAS DO BD
SELECT * FROM TB_FABRICANTE  -- RECUPERANDO AS TABELAS DO BD
SELECT * FROM TB_VEICULO -- RECUPERANDO AS TABELAS DO BD
SELECT * FROM TB_VENDAS -- RECEBENDO AS TABELAS DO BD

/*  LEMBRETE: 
Colunas de texto Nome, Descrição, Contato e Cidade serão obrigatórias, variáveis
armazenando até 50 bytes, endereço variável até 100 bytes, telefone variável de 20 bytes e
UF fixa com 2 bytes.
*/








